sudo: required
services:
  - docker
before_install:
  - docker build -t viveksjadhav/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true viveksjadhav/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-964491463939"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"